---
title: "ldt_preprocess_parcelID"
author: "Tianyu Su"
date: "8/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/su/Desktop/Research/GSD_RA/LDT")
```

```{r}

library(tidyverse)
library(sf)
library(osmextract)

library(ggplot2)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(mapview)
mapviewOptions(platform = 'leafgl')

```

1. Load 
```{r}

# laod parcel data
parcel_centroid_uniqueID <- st_read("/Users/su/Desktop/Research/GSD_RA/LDT/02_data/parcel/parcel_centroid_uniqueID.geojson")
parcel_centroid_uniqueID_sf <- st_as_sf(parcel_centroid_uniqueID)

# load POI data
pa_poi_grocery_open <- read.csv("/Users/su/Desktop/Research/GSD_RA/LDT/02_data/poi/safegraphPOI/pa_poi_grocery_open.csv")
pa_poi_grocery_open_sf <- st_as_sf(pa_poi_grocery_open, coords = c("sg_c__longitude", "sg_c__latitude"), crs = 4326, agr = "constant")

# load city boundary data
boundary <- st_read("/Users/su/Desktop/Research/GSD_RA/LDT/02_data/boundary/Pittsburgh_City_Boundary.geojson")
boundary_sf <- st_as_sf(boundary)

```

2. Preprocess
2.1 Change the CRS to EPSG:6346 (UTM zone 17N) in order to do following spatial analysis in QGIS
```{r}

parcel_centroid_uniqueID_sf
pa_poi_grocery_open_sf
boundary_sf

parcel_centroid_uniqueID_sf_6346 <- st_transform(parcel_centroid_uniqueID_sf, 6346)
pa_poi_grocery_open_sf_6346 <- st_transform(pa_poi_grocery_open_sf, 6346)
boundary_sf_6346 <- st_transform(boundary_sf, 6346)

```

3. Export
Export the processed spatial datasets.
```{r}

st_write(parcel_centroid_uniqueID_sf_6346, "02_data/parcel/parcel_centroid_uniqueID_sf_6346.geojson")
st_write(pa_poi_grocery_open_sf_6346, "02_data/poi/pa_poi_grocery_open_sf_6346.geojson")
st_write(boundary_sf_6346, "02_data/boundary/boundary_sf_6346.geojson")

```
