---
title: "ldt_transit_accessibility_routes"
author: "Tianyu Su"
date: "9/6/2021"
output: html_document
---

! I updated this script on August 2 to use the preprocessed parcel centroid data with unique IDs.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/su/Desktop/Research/GSD_RA/LDT")
```

```{r}

library(tidyverse)
library(sf)

library(ggplot2)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(mapview)
mapviewOptions(platform = 'leafgl')

```


1. Load data
```{r}

# load parcel data
parcel_centroid_uniqueID <- st_read("/Users/su/Desktop/Research/GSD_RA/LDT/02_data/parcel/parcel_centroid_uniqueID.geojson")
parcel_centroid_uniqueID_sf <- st_as_sf(parcel_centroid_uniqueID)

# load grocery store and park accessibility 
access_grocery <- read.csv("/Users/su/Desktop/Research/GSD_RA/LDT/02_data/poi/access_grocery.csv") %>%
  rename(UNIQUEID = from_id)
access_park <- read.csv("/Users/su/Desktop/Research/GSD_RA/LDT/02_data/park/access_park.csv") %>%
  rename(UNIQUEID = from_id)

```

2. Join the results with geometry

```{r}

access_grocery_geom <- parcel_centroid_uniqueID_sf %>%
  left_join(access_grocery, by = "UNIQUEID")

access_park_geom <- parcel_centroid_uniqueID_sf %>%
  left_join(access_park, by = "UNIQUEID")

write.csv(access_grocery_geom, "/Users/su/Desktop/Research/GSD_RA/LDT/02_data/poi/access_grocery_geom.csv", row.names = FALSE)
write.csv(access_park_geom, "//Users/su/Desktop/Research/GSD_RA/LDT/02_data/park/access_park.csv", row.names = FALSE)

```

