---
title: "Transportation GEO Section 3"
author: "Tianyu Su"
date: "8/10/2019"
output: 
  powerpoint_presentation:
    reference_doc: /Users/sutianyu/Dropbox (MIT)/06_MITOS/transportation-part-two/presentations/mitos_markdown_ppt_template.pptx
    slide_level: 2 # use this to override default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/sutianyu/Dropbox (MIT)/06_mitos/RStudio Projects/transportation-part-two")
```

```{r, include=FALSE}
# load libraries

library(here)

library(tidyverse)
library(ggplot2)
library(ggrepel)
library(ggthemes)
library(dplyr)
library(sf)
library(data.table)
library(lubridate)

library(maps)
library(mapdeck)
library(leaflet)
library(ggmap)
library(tmap)

library(mapview)
library(webshot)
library(htmlwidgets)
library(rbokeh)
library(rio)
# install_formats()
# webshot::install_phantomjs()

# for dot-density map
library(maptools)
library(rgeos)
library(rgdal)
library(ggthemes)

# for isochrones
library(geojsonio)

```

```{r, include=FALSE}

geo_table_sf <- st_read("proc/geo_table/geo_table.shp") %>%
  mutate(count = as.numeric(count))

geo_table_sf


geo_bg_all <- st_read("proc/geo_table/geo_block_all.shp")

nrow(geo_table_sf)
nrow(geo_bg_all)

metadata <- read.csv("proc/geo_table/geo_table_metadata.csv")

people_table <- read.csv("proc/people_table/hr-people-small-table.csv")

nrow(people_table)
head(people_table)

# exclude students
unique(pull(people_table, affiliation))

people_table_em_fa <- people_table %>%
  filter(!(affiliation == "Student"))

nrow(people_table_em_fa)

people_geoid <- read_csv("raw/raw-geospatial/all_transportation_and_hr_mit_ids_with_geoid.csv") %>%
  filter((!is.na(GEOID_FY2019)) | (!is.na(GEOID_FY2018)) | (!is.na(GEOID_FY2017)) | (!is.na(GEOID_FY2016)))

MIT_long <- -71.093510
MIT_lat <- 42.358983

```


```{r, include=FALSE}
# load boundary for large scale map (country boundary, state boundary, waterbody)

boundary_state <- st_read("raw/raw-geospatial/BOUNDARY_StateBoundary/tl_2018_us_state.shp")

# prepare the state label file
library(rgeos)

centroid <- function(sf) {
  centroid <- st_as_sf(gCentroid(as(sf, 'Spatial'),byid=TRUE))
}

state_centroids <- centroid(boundary_state$geometry) %>%
  mutate(geoid = boundary_state$GEOID) %>%
  mutate(name = boundary_state$NAME)

state_centroids
plot(state_centroids)

coord <- st_coordinates(state_centroids)

state_centroids <- cbind(state_centroids, coord) %>%
              st_set_geometry(NULL)

# load country boundary and waterbody
boundary_canada <- st_read("raw/raw-geospatial/BOUNDARY_Canada/gpr_000a11a_e.shp")
boundary_water <- st_read("raw/raw-geospatial/BOUNDARY_Water/ne_10m_ocean.shp")

```


```{r, include=FALSE}
# load boundary for medium and small scale map (city boundary, waterbody)

boundary_city <- st_read("raw/raw-geospatial/BOUNDARY_City/tl_2018_us_county.shp")

# prepare the city label file
library(rgeos)

centroid <- function(sf) {
  centroid <- st_as_sf(gCentroid(as(sf, 'Spatial'),byid=TRUE))
}

city_centroids <- centroid(boundary_city$geometry) %>%
  mutate(geoid = boundary_city$GEOID) %>%
  mutate(name = boundary_city$NAME)

city_centroids
plot(city_centroids)

coord <- st_coordinates(city_centroids)

city_centroids <- cbind(city_centroids, coord) %>%
              st_set_geometry(NULL)

head(city_centroids)

# load waterbody of MA, NH, RI, CT
boundary_water_mass <- st_read("raw/raw-geospatial/BOUNDARY_Waterbody/waterbody_mass.shp")
boundary_water_nhri <- st_read("raw/raw-geospatial/BOUNDARY_Waterbody/waterbody_NH&RI.shp")
boundary_water_ct <- st_read("raw/raw-geospatial/BOUNDARY_Waterbody/waterbody_CT.shp")

# load highway of MA
highway_mass <- st_read("raw/raw-geospatial/MassDOT_Roads_SHP/EOTMAJROADS_RTE_MAJOR.shp") %>%
  st_transform(4326)

```


```{r, include=FALSE}
# read in cycling isochrones

cycling_15 <- geojson_read(("proc/isochrones/isochrone_cycling_15.geojson"), method = "web", parse = FALSE, what = "sp")
plot(cycling_15)
cycling_15_sf <- st_as_sf(cycling_15)

cycling_30 <- geojson_read(("proc/isochrones/isochrone_cycling_30.geojson"), method = "web", parse = FALSE, what = "sp")
plot(cycling_30)
cycling_30_sf <- st_as_sf(cycling_30)

cycling_45 <- geojson_read(("proc/isochrones/isochrone_cycling_45.geojson"), method = "web", parse = FALSE, what = "sp")
plot(cycling_45)
cycling_45_sf <- st_as_sf(cycling_45)

cycling_60 <- geojson_read(("proc/isochrones/isochrone_cycling_60.geojson"), method = "web", parse = FALSE, what = "sp")
plot(cycling_60)
cycling_60_sf <- st_as_sf(cycling_60)

```


```{r, include=FALSE}
# read in driving isochrones

driving_15 <- geojson_read(("proc/isochrones/isochrone_driving_15.geojson"), method = "web", parse = FALSE, what = "sp")
plot(driving_15)
driving_15_sf <- st_as_sf(driving_15)

driving_30 <- geojson_read(("proc/isochrones/isochrone_driving_30.geojson"), method = "web", parse = FALSE, what = "sp")
plot(driving_30)
driving_30_sf <- st_as_sf(driving_30)

driving_45 <- geojson_read(("proc/isochrones/isochrone_driving_45.geojson"), method = "web", parse = FALSE, what = "sp")
plot(driving_45)
driving_45_sf <- st_as_sf(driving_45)

driving_60 <- geojson_read(("proc/isochrones/isochrone_driving_60.geojson"), method = "web", parse = FALSE, what = "sp")
plot(driving_60)
driving_60_sf <- st_as_sf(driving_60)

```


```{r, include=FALSE}
# read in walking isochrones

walking_15 <- geojson_read(("proc/isochrones/isochrone_walking_15.geojson"), method = "web", parse = FALSE, what = "sp")
plot(walking_15)
walking_15_sf <- st_as_sf(walking_15)

walking_30 <- geojson_read(("proc/isochrones/isochrone_walking_30.geojson"), method = "web", parse = FALSE, what = "sp")
plot(walking_30)
walking_30_sf <- st_as_sf(walking_30)

walking_45 <- geojson_read(("proc/isochrones/isochrone_walking_45.geojson"), method = "web", parse = FALSE, what = "sp")
plot(walking_45)
walking_45_sf <- st_as_sf(walking_45)

walking_60 <- geojson_read(("proc/isochrones/isochrone_walking_60.geojson"), method = "web", parse = FALSE, what = "sp")
plot(walking_60)
walking_60_sf <- st_as_sf(walking_60)

```


```{r, include=FALSE}
# generate centroid points of blocks

library(rgeos)

centroid <- function(sf) {
  centroid <- st_as_sf(gCentroid(as(sf, 'Spatial'),byid=TRUE))
}

block_centroids <- centroid(geo_table_sf$geometry) %>%
  mutate(geoid = geo_table_sf$geoid)

block_centroids
plot(block_centroids)

```


```{r, include=FALSE}
# select blocks whose centroids are in isochrone-driving 60 (medium scale) and set bounding box

block_centroids <- block_centroids %>% 
  st_set_crs(4326)

block_centroids_in <- st_join(block_centroids, driving_60_sf, left = FALSE)

geoid_60 <- unique(pull(block_centroids_in, geoid))
head(geoid_60,5)

geo_table_60_sf <- geo_table_sf %>%
  filter(geoid %in% geoid_60)

```

```{r, include=FALSE}

bb_bg = st_bbox(driving_60_sf)

bb_bg[1]
bb_bg[2]
bb_bg[3]
bb_bg[4]

```


```{r, include=FALSE}
# select blocks whose centroids are in isochrone-driving 30 (small scale) and set bounding box

block_centroids <- block_centroids %>% 
  st_set_crs(4326)

block_centroids_in <- st_join(block_centroids, driving_30_sf, left = FALSE)

geoid_30 <- unique(pull(block_centroids_in, geoid))
head(geoid_30,5)

geo_table_30_sf <- geo_table_sf %>%
  filter(geoid %in% geoid_30)

```

```{r, include=FALSE}

bb_bg = st_bbox(driving_30_sf)

bb_bg[1]
bb_bg[2]
bb_bg[3]
bb_bg[4]

```


```{r, include=FALSE}
# prepare 2018 data (employees/faculties/students)
# prepare 2018 data (employees/faculties)

head(people_table)
head(people_geoid)

people_geoid_2018 <- people_geoid %>%
  dplyr::select(MITID,
                GEOID_FY2018) %>%
  rename(mit_id = MITID) %>%
  rename(geoid = GEOID_FY2018)

people_table_2018 <- people_table %>%
  filter(parking_year == 2018) %>%
  left_join(people_geoid_2018, by = 'mit_id') 

people_table_2018 %>%
  filter((!is.na(geoid)))

# 27187/42020 = 64.7% of 2018 employees/faculties/students have geoid

people_table_2018

people_table_2018 %>%
  filter((!is.na(geoid))) %>%
  group_by(geoid) %>%
  summarise(count_2018 = n()) %>%
  arrange(desc(count_2018))

people_table_2018_ef <- people_table_2018 %>%
  filter((!is.na(geoid))) %>%
  filter(affiliation == "Employee" | affiliation == "Faculty")

people_table_2018_ef

# 12294 of employees/faculties have goeid

people_table_2018_forjoin <- people_table_2018 %>%
  filter((!is.na(geoid))) %>%
  group_by(geoid) %>%
  summarise(count_2018 = n()) %>%
  arrange(desc(count_2018)) 

geo_people_2018 <- geo_table_sf %>%
  inner_join(people_table_2018_forjoin, by = 'geoid') %>%
  mutate(count_2018 = as.numeric(count_2018))

geo_people_2018
class(geo_people_2018)

sum(geo_people_2018$count_2018)

# 26726/27187 = 98.3% of the employees/faculties/students with geoid are in the top 11 state

people_table_2018_ef_forjoin <- people_table_2018_ef %>%
  filter((!is.na(geoid))) %>%
  group_by(geoid) %>%
  summarise(count_2018 = n()) %>%
  arrange(desc(count_2018)) 

geo_people_2018_ef <- geo_table_sf %>%
  inner_join(people_table_2018_ef_forjoin, by = 'geoid') %>%
  mutate(count_2018 = as.numeric(count_2018))

geo_people_2018_ef
class(geo_people_2018_ef)

sum(geo_people_2018_ef$count_2018)

# 12029/12294 = 97.8% of the employees/faculties with geoid are in the top 11 state

```

# prepare permit data
```{r}

permit <- read.csv("proc/permits-processed-permit-letters-person-level.csv")
permit_18 <- permit %>%
  filter(parking_year == "PY18") %>%
  rename(mit_id = accountnumber)

permit_18
# in PY2018, there are 6522 employees/faculty/students have parking permits

people_permit_18 <- permit_18 %>%
  inner_join(people_table_2018_ef, by = "mit_id")

people_permit_18
# in PY2018, there are 4,512 employees/faculty have parking permits and geoid

people_permit_2018_forjoin <- people_permit_18 %>%
  filter((!is.na(geoid))) %>%
  group_by(geoid) %>%
  summarise(count_permit_2018 = n()) %>%
  arrange(desc(count_permit_2018))

people_permit_2018_forjoin
sum(people_permit_2018_forjoin$count_permit_2018)
# in PY2018, there are 4,512 employees/faculty have parking permits and geoid

geo_permit_2018 <- geo_table_sf %>%
  inner_join(people_permit_2018_forjoin, by = 'geoid') %>%
  mutate(count_permit_2018 = as.numeric(count_permit_2018))

geo_permit_2018
sum(geo_permit_2018$count_permit_2018)

# 4501/4512 = 99.8% of the PY2018 permit holders are in the top 11 state

```

******************* SECTION3: TRAVEL TIME *******************

******************* travel time map *******************

```{r, include=FALSE}

geo_people_2018_forjoin <- geo_people_2018 %>%
  dplyr::select(geoid, count_2018) %>%
  st_set_geometry(NULL)

geo_people_2018_ef_forjoin <- geo_people_2018_ef %>%
  dplyr::select(geoid, count_2018) %>%
  rename(ef_2018 = count_2018) %>%
  st_set_geometry(NULL)

geo_permit_2018_forjoin <- geo_permit_2018 %>%
  dplyr::select(geoid, count_permit_2018) %>%
  st_set_geometry(NULL)

geo_people_2018_forjoin
geo_people_2018_ef_forjoin
geo_permit_2018_forjoin

```

# ```{r, include=FALSE}
# # ratio of transit/ratio
# 
# map_ratio <- ggplot(geo_table_sf) +
#   geom_sf(data = boundary_state, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
#   geom_sf(data = boundary_canada, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
#   geom_sf(data = boundary_water, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
#   geom_sf(aes(fill = T_Time/D_M_Tim), color = "white", size = .001, show.legend = TRUE) +
#   scale_fill_gradient(low="#007fb0", high="#e42f3f") +
#   coord_sf(xlim = c(-80.42745, -69.8), ylim = c(36.78677, 45.34768)) +
#   geom_label(data = state_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold")
# 
# map_ratio
# 
# ggsave("visual/map_ratio.png", plot = map_ratio, device = NULL, path = NULL,
#   scale = 1, width = 30, height = 30, units = "cm",
#   dpi = 300, limitsize = TRUE)
# 
# ```

```{r, include=FALSE}
# prepare the dataset

geo_table_sf_valid <- geo_table_sf %>%
  filter(!is.na(D_M_Tim)) 

geo_table_sf_valid

geo_table_sf_valid[is.na(geo_table_sf_valid)] <- 1000000

geo_table_sf_valid <- geo_table_sf_valid %>%
  left_join(geo_people_2018_forjoin, by = 'geoid') %>%
  left_join(geo_people_2018_ef_forjoin, by = 'geoid') %>%
  left_join(geo_permit_2018_forjoin, by = 'geoid') 

geo_table_sf_valid

geo_table_sf_wt <- geo_table_sf_valid %>%
  mutate(D_Time_R = D_M_Tim + 5*60) %>%
  mutate(min_WT = pmin(W_Time, T_Time)) %>%
  mutate(diff_in_min = (min_WT - D_Time_R)/60) %>%
  mutate(diff_in_min_T_D = (T_Time - D_Time_R)/60) %>%
  mutate(diff_in_min_W_D = (W_Time - D_Time_R)/60)

head(geo_table_sf_wt)

# geo_table_sf_wtb <- geo_table_sf_valid %>%
#   mutate(D_Time_R = D_M_Tim + 10*60) %>%
#   mutate(min_WTB = pmin(W_Time, T_Time, B_Time)) %>%
#   mutate(diff_WTB = min_WTB - D_Time_R)
# 
# head(geo_table_sf_wt)
# head(geo_table_sf_wtb)

```

# ```{r, include=FALSE}
# # test mapping for the largest scale
# 
# map_diff <- ggplot() +
#   geom_sf(data = boundary_state, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
#   geom_sf(data = boundary_canada, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
#   geom_sf(data = boundary_water, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
#   geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
#   geom_sf(data = geo_table_sf_wt, aes(fill = diff_WT/60), color = "white", size = .001, show.legend = TRUE) +
#   scale_fill_gradient(low="#007fb0", high="#e42f3f") +
#   coord_sf(xlim = c(-80.42745, -69.8), ylim = c(36.78677, 45.34768)) +
#   geom_label(data = state_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold")
# 
# map_diff
# 
# ggsave("visual/map_diff.png", plot = map_diff, device = NULL, path = NULL,
#   scale = 1, width = 30, height = 30, units = "cm",
#   dpi = 300, limitsize = TRUE)
# 
# ```

# mapping 191215
```{r, include=FALSE}

geo_table_sf_wt_T_D_60 <- geo_table_sf_wt %>%
  filter(diff_in_min_T_D <= 60)

geo_table_sf_wt_T_D_60

map_diff_60_T_D <- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_sf_wt, fill = "grey", color = 'white', size = .1, show.legend = TRUE, alpha = 0.65) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_60_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_sf_wt_T_D_60, aes(fill = diff_in_min_T_D), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_gradient(low="#007fb0", high="#e42f3f") +
  coord_sf(xlim = c(-72.14123, -70.54279 ), ylim = c(41.67098, 43.07718)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)


ggsave("visual/map_diff_60_T_D_191215.png", plot = map_diff_60_T_D, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)


geo_table_sf_wt_W_D_60 <- geo_table_sf_wt %>%
  filter(diff_in_min_W_D <= 60)

geo_table_sf_wt_W_D_60

map_diff_60_W_D <- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_sf_wt, fill = "grey", color = 'white', size = .1, show.legend = TRUE, alpha = 0.65) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_60_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_sf_wt_W_D_60, aes(fill = diff_in_min_W_D), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_gradient(low="#007fb0", high="#e42f3f") +
  coord_sf(xlim = c(-72.14123, -70.54279 ), ylim = c(41.67098, 43.07718)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)


ggsave("visual/map_diff_60_W_D_191215.png", plot = map_diff_60_W_D, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)

```

```{r}

map_diff_60_b <- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018_60, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_60_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_60_sf_wtb, aes(fill = diff_WTB/60), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_gradient(low="#007fb0", high="#e42f3f", limits = c(min(geo_table_60_sf_wt$diff_WT/60), max(geo_table_60_sf_wt$diff_WT/60))) +
  coord_sf(xlim = c(-72.14123, -70.54279 ), ylim = c(41.67098, 43.07718)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)

map_diff_60_b

ggsave("visual/map_diff_60_b.png", plot = map_diff_60_b, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)

```

```{r, include=FALSE}

map_diff_30 <- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018_30, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_30_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_30_sf_wt, aes(fill = diff_WT/60), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_gradient(low="#007fb0", high="#e42f3f") +
  coord_sf(xlim = c(-71.56551, -70.85817), ylim = c(42.09288, 42.69501)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)

map_diff_30

ggsave("visual/map_diff_30.png", plot = map_diff_30, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)


map_diff_30_b <- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018_30, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_30_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_30_sf_wtb, aes(fill = diff_WTB/60), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_gradient(low="#007fb0", high="#e42f3f", limits = c(min(geo_table_30_sf_wt$diff_WT/60), max(geo_table_30_sf_wt$diff_WT/60))) +
  coord_sf(xlim = c(-71.56551, -70.85817), ylim = c(42.09288, 42.69501)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)

map_diff_30_b

ggsave("visual/map_diff_30_b.png", plot = map_diff_30_b, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)

```


```{r, include=FALSE}
# Transit + Walking

geo_table_sf_wt[is.na(geo_table_sf_wt)] <- 0

geo_table_sf_wt_0 <- geo_table_sf_wt %>%
  filter(diff_WT <= 0)

sum(geo_table_sf_wt_0$count_2018)
sum(geo_table_sf_wt_0$ef_2018)
sum(geo_table_sf_wt_0$count_permit_2018)

# 11188/27187 = 41.2% of the employees/faculties/students with geoid live in blocks with transit/walking time less than or equal to driving time
# 2254/12294 = 18.3% of the employees/faculties with geoid live in blocks with transit/walking time less than or equal to driving time
# 597/4982 = 12.0% of the 2018 permit holders with geoid live in blocks with transit/walking time less than or equal to driving time

geo_table_sf_wt_15 <- geo_table_sf_wt %>%
  filter(diff_WT <= 900)

sum(geo_table_sf_wt_15$count_2018)
sum(geo_table_sf_wt_15$ef_2018)
sum(geo_table_sf_wt_15$count_permit_2018)

# 16479/27187 = 60.6% of the employees/faculties/students with geoid live in blocks with transit/walking time less than or equal to driving time + 15 min
# 5520/12294 = 44.9% of the employees/faculties with geoid live in blocks with transit/walking time less than or equal to driving time + 15 min
# 1387/4982 = 27.8% of the 2018 permit holders with geoid live in blocks with transit/walking time less than or equal to driving time + 15 min

geo_table_sf_wt_30 <- geo_table_sf_wt %>%
  filter(diff_WT <= 1800)

sum(geo_table_sf_wt_30$count_2018)
sum(geo_table_sf_wt_30$ef_2018)
sum(geo_table_sf_wt_30$count_permit_2018)

# 19370/27187 = 71.2% of the employees/faculties/students with geoid live in blocks with transit/walking time less than or equal to driving time + 30 min
# 7771/12294 = 63.2% of the employees/faculties with geoid live in blocks with transit/walking time less than or equal to driving time + 30 min
# 2464/4982 = 49.5% of the 2018 permit holders with geoid live in blocks with transit/walking time less than or equal to driving time + 30 min

```


```{r, include=FALSE}

geo_table_30_sf_wt_0 <- geo_table_30_sf_wt %>%
  filter(diff_WT <= 0)

geo_table_30_sf_wt_15 <- geo_table_30_sf_wt %>%
  filter(diff_WT <= 900)

geo_table_30_sf_wt_30 <- geo_table_30_sf_wt %>%
  filter(diff_WT <= 1800)

geo_table_30_sf_wt_0
geo_table_30_sf_wt_15
geo_table_30_sf_wt_30

```

```{r, include=FALSE}

map_diff_30_0 <- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018_30, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_30_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_30_sf_wt_0, aes(fill = log(count_2018)), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_distiller(palette = "OrRd", trans = "reverse", limits = c(min(geo_table_30_sf_wt_30$count_2018), max(geo_table_30_sf_wt_30$count_2018))) + 
  coord_sf(xlim = c(-71.56551, -70.85817), ylim = c(42.09288, 42.69501)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)

map_diff_30_0

ggsave("visual/map_diff_30_0.png", plot = map_diff_30_0, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)


map_diff_30_15 <- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018_30, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_30_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_30_sf_wt_15, aes(fill = log(count_2018)), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_distiller(palette = "OrRd", trans = "reverse", limits = c(min(geo_table_30_sf_wt_30$count_2018), max(geo_table_30_sf_wt_30$count_2018))) + 
  coord_sf(xlim = c(-71.56551, -70.85817), ylim = c(42.09288, 42.69501)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)

map_diff_30_15

ggsave("visual/map_diff_30_15.png", plot = map_diff_30_15, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)


map_diff_30_30 <- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018_30, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_30_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_30_sf_wt_30, aes(fill = log(count_2018)), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_distiller(palette = "OrRd", trans = "reverse", limits = c(min(geo_table_30_sf_wt_30$count_2018), max(geo_table_30_sf_wt_30$count_2018))) + 
  coord_sf(xlim = c(-71.56551, -70.85817), ylim = c(42.09288, 42.69501)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)

map_diff_30_30

ggsave("visual/map_diff_30_30.png", plot = map_diff_30_30, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)

```


```{r, include=FALSE}
# Transit + Walking + Cycling

geo_table_sf_wtb[is.na(geo_table_sf_wtb)] <- 0

geo_table_sf_wtb_0 <- geo_table_sf_wtb %>%
  filter(diff_WTB <= 0)

sum(geo_table_sf_wtb_0$count_2018)
sum(geo_table_sf_wtb_0$ef_2018)
sum(geo_table_sf_wtb_0$count_permit_2018)

# 16310/27187 = 60.0% of the employees/faculties/students with geoid live in blocks with transit/walking/cycling time less than or equal to driving time
# 5315/12294 = 43.2% of the employees/faculties with geoid live in blocks with transit/walking/cycling time less than or equal to driving time
# 1262/4982 = 25.3% of the 2018 permit holders with geoid live in blocks with transit/walking/cycling time less than or equal to driving time

geo_table_sf_wtb_15 <- geo_table_sf_wtb %>%
  filter(diff_WTB <= 900)

sum(geo_table_sf_wtb_15$count_2018)
sum(geo_table_sf_wtb_15$ef_2018)
sum(geo_table_sf_wtb_15$count_permit_2018)

# 18928/27187 = 69.6% of the employees/faculties/students with geoid live in blocks with transit/walking/cycling time less than or equal to driving time + 15 min
# 7407/12294 = 60.2% of the employees/faculties with geoid live in blocks with transit/walking/cycling time less than or equal to driving time + 15 min
# 2292/4982 = 46.0% of the 2018 permit holders with geoid live in blocks with transit/walking/cycling time less than or equal to driving time + 15 min

geo_table_sf_wtb_30 <- geo_table_sf_wtb %>%
  filter(diff_WTB <= 1800)

sum(geo_table_sf_wtb_30$count_2018)
sum(geo_table_sf_wtb_30$ef_2018)
sum(geo_table_sf_wtb_30$count_permit_2018)

# 20857/27187 = 76.7% of the employees/faculties/students with geoid live in blocks with transit/walking/cycling time less than or equal to driving time + 30 min
# 8897/12294 = 72.4% of the employees/faculties with geoid live in blocks with transit/walking/cycling time less than or equal to driving time + 30 min
# 3154/4982 = 63.3% of the 2018 permit holders with geoid live in blocks with transit/walking/cycling time less than or equal to driving time + 30 min

```


```{r, include=FALSE}

geo_table_30_sf_wtb_0 <- geo_table_30_sf_wtb %>%
  filter(diff_WTB <= 0)

geo_table_30_sf_wtb_15 <- geo_table_30_sf_wtb %>%
  filter(diff_WTB <= 900)

geo_table_30_sf_wtb_30 <- geo_table_30_sf_wtb %>%
  filter(diff_WTB <= 1800)

geo_table_30_sf_wtb_0
geo_table_30_sf_wtb_15
geo_table_30_sf_wtb_30

```

```{r, include=FALSE}

map_diff_30_0_b <- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018_30, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_30_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_30_sf_wtb_0, aes(fill = log(count_2018)), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_distiller(palette = "OrRd", trans = "reverse", limits = c(min(geo_table_30_sf_wtb_30$count_2018), max(geo_table_30_sf_wtb_30$count_2018))) + 
  coord_sf(xlim = c(-71.56551, -70.85817), ylim = c(42.09288, 42.69501)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)

map_diff_30_0_b

ggsave("visual/map_diff_30_0_b.png", plot = map_diff_30_0_b, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)


map_diff_30_15_b <- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018_30, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_30_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_30_sf_wtb_15, aes(fill = log(count_2018)), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_distiller(palette = "OrRd", trans = "reverse", limits = c(min(geo_table_30_sf_wtb_30$count_2018), max(geo_table_30_sf_wtb_30$count_2018))) + 
  coord_sf(xlim = c(-71.56551, -70.85817), ylim = c(42.09288, 42.69501)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)

map_diff_30_15_b

ggsave("visual/map_diff_30_15_b.png", plot = map_diff_30_15_b, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)


map_diff_30_30_b<- ggplot() +
  geom_sf(data = boundary_city, fill = "white", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = geo_people_2018_30, fill = "white", color = 'white', size = .1, show.legend = TRUE, alpha = 0) +
  geom_sf(data = boundary_water_mass, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_nhri, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = boundary_water_ct, fill = "grey50", color = 'grey', size = 0.5, alpha = 1, show.legend = FALSE) +
  geom_sf(data = highway_mass, fill = "white", color = 'grey', size = 1, alpha = 0, show.legend = FALSE) +
  geom_sf(data = driving_30_sf, fill = "white", color = "#e42f3f", size = 0.5, show.legend = TRUE, alpha = 0) +
  geom_sf(data = geo_table_30_sf_wtb_30, aes(fill = log(count_2018)), color = "white", size = .001, show.legend = TRUE) +
  scale_fill_distiller(palette = "OrRd", trans = "reverse", limits = c(min(geo_table_30_sf_wtb_30$count_2018), max(geo_table_30_sf_wtb_30$count_2018))) + 
  coord_sf(xlim = c(-71.56551, -70.85817), ylim = c(42.09288, 42.69501)) +
  geom_label(data = city_centroids, aes(X, Y, label = name), fill = "black", colour = "white", fontface = "bold", label.size = 0.25)

map_diff_30_30_b

ggsave("visual/map_diff_30_30_b.png", plot = map_diff_30_30_b, device = NULL, path = NULL,
  scale = 1, width = 30, height = 30, units = "cm",
  dpi = 300, limitsize = TRUE)

```


